# Generated by Django 3.2.7 on 2021-10-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('tg_id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Телеграм ID')),
                ('tg_name', models.CharField(max_length=32, verbose_name='Имя пользователя в Телеграм')),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'пользователя бота',
                'verbose_name_plural': 'пользователи бота',
                'db_table': 'member',
            },
        ),
    ]
