# Generated by Django 3.2.7 on 2021-11-02 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0002_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberState',
            fields=[
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='useradmin.member', verbose_name='Пользователь')),
                ('main_message_id', models.PositiveIntegerField(verbose_name='id основного сообщения')),
                ('pin_message_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='id закрепленного сообщения')),
            ],
            options={
                'verbose_name': 'состояние пользователя бота ',
                'verbose_name_plural': 'состояния пользователей бота',
                'db_table': 'member_state',
            },
        ),
    ]
