# Generated by Django 3.2.7 on 2021-11-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0004_alter_member_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='member',
            name='tg_name',
            field=models.CharField(max_length=32, null=True, verbose_name='Имя пользователя в Телеграм'),
        ),
    ]
