# Generated by Django 3.2.7 on 2021-11-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0005_auto_20211108_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberstate',
            name='state',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Положение пользователя'),
        ),
    ]
