# Generated by Django 3.2.7 on 2021-11-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0009_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, default=True, max_length=254, verbose_name='email address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telegram_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Телеграм ID'),
        ),
    ]
