# Generated by Django 3.2.7 on 2021-11-27 12:43

from django.db import migrations, models
import django_admin.apps.useradmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0010_auto_20211119_0941'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', django_admin.apps.useradmin.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=True, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
