# Generated by Django 3.2.7 on 2021-12-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0013_alter_customgroup_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='region',
            field=models.CharField(default=None, max_length=256, null=True, verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='member',
            name='unit',
            field=models.CharField(default=None, max_length=256, null=True, verbose_name='Департамент'),
        ),
    ]
