# Generated by Django 3.2.7 on 2022-02-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0017_alter_memberstate_has_init_poll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telegram_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Телеграм ID'),
        ),
        migrations.AlterField(
            model_name='member',
            name='tg_id',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False, verbose_name='Телеграм ID'),
        ),
    ]
