# Generated by Django 3.2.7 on 2022-06-21 10:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('useradmin', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=4096, verbose_name='Текст вопроса')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('picture', models.ImageField(blank=True, default=None, max_length=1024, null=True, upload_to='game_picture/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Изображение')),
                ('cash', models.CharField(max_length=128, null=True, verbose_name='Кэш фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('owner', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_question', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'вопрос к интерактиву',
                'verbose_name_plural': 'вопросы к интерактиву',
                'ordering': ('add_date',),
            },
        ),
        migrations.CreateModel(
            name='QuestionOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=64, verbose_name='Текст варианта')),
                ('true_answer', models.BooleanField(verbose_name='Верный ответ?')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option', to='game.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'варианты ответов',
                'verbose_name_plural': 'варианты ответов',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата ответа')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gquestion_answer', to='useradmin.member', verbose_name='Пользователь')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.questionoptions', verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'ответ на вопрос',
                'verbose_name_plural': 'ответы на вопросы',
            },
        ),
    ]
