# Generated by Django 3.2.7 on 2021-10-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_answer_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='picture',
            field=models.ImageField(blank=True, default=None, max_length=1024, null=True, upload_to='game_picture/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
