# Generated by Django 3.2.7 on 2021-11-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_question_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='cash',
            field=models.CharField(max_length=128, null=True, verbose_name='Кэш фото'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(max_length=4096, verbose_name='Текст вопроса'),
        ),
    ]
