# Generated by Django 3.2.7 on 2021-11-17 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_question_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.questionoptions', verbose_name='Ответ'),
        ),
    ]
