# Generated by Django 3.2.7 on 2022-06-21 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('useradmin', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'опрос',
                'verbose_name_plural': 'опросы',
                'db_table': 'polls',
            },
        ),
        migrations.CreateModel(
            name='QuestionOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_key', models.PositiveSmallIntegerField(verbose_name='Количество кнопок')),
                ('text_key', models.CharField(help_text='Надписи кнопок записываются в строчку и разделяются ";"', max_length=256, verbose_name='Текст кнопок')),
            ],
            options={
                'verbose_name': 'кнопки ответов',
                'verbose_name_plural': 'кнопки ответов',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=4096, verbose_name='Текст вопроса')),
                ('text_answer', models.BooleanField(verbose_name='Возможен ответ текстом?')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('options', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poll.questionoptions', verbose_name='Варианты ответа')),
                ('owner', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poll_question', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question', to='poll.poll', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'вопрос к опросу',
                'verbose_name_plural': 'вопросы',
                'ordering': ('add_date', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=256, verbose_name='Ответ')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата ответа')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pquestion_answer', to='useradmin.member', verbose_name='Пользователь')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pquestion_answer', to='poll.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'ответ к вопросу',
                'verbose_name_plural': 'ответы к вопросам',
                'unique_together': {('member', 'question', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата ответа')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_answer', to='useradmin.member', verbose_name='Пользователь')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='poll_answer', to='poll.poll', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'ответ на опрос',
                'verbose_name_plural': 'ответы на опросы',
                'unique_together': {('member', 'poll', 'date')},
            },
        ),
    ]
