# Generated by Django 3.2.7 on 2021-10-27 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('call_support', '0004_alter_memberquestion_member'),
        ('useradmin', '0002_member'),
        ('game', '0003_alter_answer_member'),
        ('poll', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_answer', to='useradmin.member', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pquestion_answer', to='useradmin.member', verbose_name='Пользователь'),
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
