# Generated by Django 3.2.7 on 2021-11-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20211027_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(max_length=4096, verbose_name='Текст вопроса'),
        ),
    ]
