# Generated by Django 3.2.7 on 2022-01-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0016_memberstate_has_init_poll'),
        ('poll', '0006_alter_answer_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата ответа'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата ответа'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('member', 'poll', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='questionanswer',
            unique_together={('member', 'question', 'date')},
        ),
    ]
