# Generated by Django 3.2.7 on 2021-10-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True, verbose_name='Ответ')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата вопроса')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата ответа')),
            ],
            options={
                'verbose_name': 'ответ',
                'verbose_name_plural': 'вопросы пользователей',
            },
        ),
        migrations.CreateModel(
            name='MemberQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Вопрос')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата ответа')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'вопросы пользователей',
            },
        ),
    ]
