# Generated by Django 3.2.7 on 2022-06-21 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('useradmin', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PinMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Для отображения ссылок в сообщении воспользуйтесь конструкцией [текст](ссылка)', max_length=4096, verbose_name='Текст сообщения')),
            ],
            options={
                'verbose_name': 'закрепленное сообщение',
                'verbose_name_plural': 'закрепленное сообщение',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Для отображения ссылок в сообщении воспользуйтесь конструкцией [текст](ссылка)', max_length=4096, verbose_name='Текст сообщения')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата рассылки')),
                ('picture', models.ImageField(blank=True, default=None, max_length=1024, null=True, upload_to='newsletter/%Y/%m/%d', verbose_name='Изображение')),
                ('cash', models.CharField(max_length=128, null=True, verbose_name='Кэш фото')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='newsletter', to=settings.AUTH_USER_MODEL, verbose_name='Оператор')),
            ],
            options={
                'verbose_name': 'новое сообщение',
                'verbose_name_plural': 'Рассылка сообщений',
            },
        ),
        migrations.CreateModel(
            name='MemberQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1900, verbose_name='Вопрос')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата ответа')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_question', to='useradmin.member', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'вопросы пользователей',
            },
        ),
        migrations.CreateModel(
            name='AnswerOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Максимальное количество символов в ответе 1900 \n                                       | Для отображения ссылок в сообщении воспользуйтесь конструкцией \n                                       [текст](ссылка)', max_length=1900, null=True, verbose_name='Ответ')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата вопроса')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата ответа')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='call_support.memberquestion', verbose_name='Вопрос')),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_question_answer', to=settings.AUTH_USER_MODEL, verbose_name='Оператор')),
            ],
            options={
                'verbose_name': 'ответ',
                'verbose_name_plural': 'вопросы пользователей',
            },
        ),
    ]
