# Generated by Django 3.2.7 on 2021-10-27 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0002_member'),
        ('call_support', '0003_answeroperator_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberquestion',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_question', to='useradmin.member', verbose_name='Пользователь'),
        ),
    ]
