# Generated by Django 3.2.7 on 2021-11-07 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('call_support', '0005_pinmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pinmessage',
            options={'verbose_name': 'закрепленное сообщение', 'verbose_name_plural': 'закрепленное сообщение'},
        ),
        migrations.AlterField(
            model_name='pinmessage',
            name='text',
            field=models.TextField(help_text='Для отображения ссылок в сообщении воспользуйтесь конструкцией [текст](ссылка)', verbose_name='Текст сообщения'),
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Для отображения ссылок в сообщении воспользуйтесь конструкцией [текст](ссылка)', verbose_name='Текст сообщения')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата вопроса')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='newsletter', to=settings.AUTH_USER_MODEL, verbose_name='Оператор')),
            ],
            options={
                'verbose_name': 'новое сообщение',
                'verbose_name_plural': 'Рассылка сообщений',
            },
        ),
    ]
