# Generated by Django 3.2.7 on 2021-11-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_support', '0006_auto_20211107_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeroperator',
            name='text',
            field=models.TextField(max_length=4096, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='text',
            field=models.TextField(help_text='Для отображения ссылок в сообщении воспользуйтесь конструкцией [текст](ссылка)', max_length=4096, verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='pinmessage',
            name='text',
            field=models.TextField(help_text='Для отображения ссылок в сообщении воспользуйтесь конструкцией [текст](ссылка)', max_length=4096, verbose_name='Текст сообщения'),
        ),
    ]
