# Generated by Django 3.2.7 on 2021-11-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_support', '0007_auto_20211108_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='cash',
            field=models.CharField(max_length=128, null=True, verbose_name='Кэш фото'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='picture',
            field=models.ImageField(blank=True, default=None, max_length=1024, null=True, upload_to='newsletter/%Y/%m/%d', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата рассылки'),
        ),
    ]
