# Generated by Django 3.2.7 on 2021-11-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_support', '0010_auto_20211118_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeroperator',
            name='text',
            field=models.TextField(help_text='Максимальное количество символов в ответе 1900', max_length=1900, null=True, verbose_name='Ответ'),
        ),
    ]
